# Generated by Django 5.1 on 2024-10-25 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id_organization', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id_payment_method', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id_payment_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order_date', models.DateField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.client')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id_catalog', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_organization', models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization')),
            ],
            options={
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='OrgConfig',
            fields=[
                ('id_org_config', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido_inicial', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_superior', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_organization', models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization')),
            ],
            options={
                'db_table': 'org_config',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('image_link_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_catalog', models.ForeignKey(blank=True, db_column='id_catalog', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.catalog')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_order', models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.order')),
                ('id_product', models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.product')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id_product_category', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_category', models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.category')),
                ('id_product', models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.product')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('receipt_date', models.DateField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_order', models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.order')),
                ('id_payment_method', models.ForeignKey(blank=True, db_column='id_payment_method', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.paymentmethod')),
                ('id_payment_status', models.ForeignKey(blank=True, db_column='id_payment_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.paymentstatus')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_organization', models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='SectorCategory',
            fields=[
                ('id_sector_category', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('id_category', models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.category')),
                ('id_sector', models.ForeignKey(blank=True, db_column='id_sector', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.sector')),
            ],
            options={
                'db_table': 'sector_category',
            },
        ),
    ]
