# Generated by Django 5.1 on 2024-10-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0002_remade_database'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orgconfig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sectorcategory',
            options={'managed': True},
        ),
    ]
