# Generated by Django 5.1 on 2024-10-24 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0003_alter_catalog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='id_org',
            new_name='id_organization',
        ),
        migrations.RemoveField(
            model_name='category',
            name='svg_path',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='attendant',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='status',
        ),
        migrations.AddField(
            model_name='catalog',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.order'),
        ),
        migrations.AddField(
            model_name='detail',
            name='id_product',
            field=models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.client'),
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='orgconfig',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='id_catalog',
            field=models.ForeignKey(blank=True, db_column='id_catalog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='id_product',
            field=models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='id_product_category',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.order'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_payment_method',
            field=models.ForeignKey(blank=True, db_column='id_payment_method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.paymentmethod'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_payment_status',
            field=models.ForeignKey(blank=True, db_column='id_payment_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.paymentstatus'),
        ),
        migrations.AddField(
            model_name='sector',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.organization'),
        ),
        migrations.AddField(
            model_name='sectorcategory',
            name='id_category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.category'),
        ),
        migrations.AddField(
            model_name='sectorcategory',
            name='id_sector',
            field=models.ForeignKey(blank=True, db_column='id_sector', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.sector'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id_category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermenu.category'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
