# Generated by Django 5.1 on 2024-10-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0004_rename_id_org_organization_id_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orgconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectorcategory',
            options={},
        ),
    ]
