# Generated by Django 5.1 on 2024-10-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermenu', '0005_alter_catalog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.order'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='id_product',
            field=models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.client'),
        ),
        migrations.AlterField(
            model_name='orgconfig',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_catalog',
            field=models.ForeignKey(blank=True, db_column='id_catalog', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.catalog'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id_category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id_product',
            field=models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.product'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.order'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_payment_method',
            field=models.ForeignKey(blank=True, db_column='id_payment_method', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_payment_status',
            field=models.ForeignKey(blank=True, db_column='id_payment_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='id_organization',
            field=models.ForeignKey(blank=True, db_column='id_organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.organization'),
        ),
        migrations.AlterField(
            model_name='sectorcategory',
            name='id_category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.category'),
        ),
        migrations.AlterField(
            model_name='sectorcategory',
            name='id_sector',
            field=models.ForeignKey(blank=True, db_column='id_sector', null=True, on_delete=django.db.models.deletion.CASCADE, to='usermenu.sector'),
        ),
    ]
